"""initial migration

Revision ID: 3af5f49bfd9
Revises: None
Create Date: 2016-03-26 16:12:13.228000

"""

# revision identifiers, used by Alembic.
revision = '3af5f49bfd9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_biography', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_biography')
    op.create_table('entry_tag_reg',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=True),
    sa.Column('entry_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], [u'entries.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], [u'tagTable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
